export type Entry = {
  duration: number;
  contentURL: string; // URL
  groupTitle?: string;
  entryTitle?: string;
  tvgId?: string;
  tvgLogo?: string;
  tvgName?: string;
  tvgCountry?: any;
  tvgLanguage?: any;
  tvgType?: any;
  tvgUrl?: any;
  tvgGroup?: any;
  tvgEpgid?: any;
  tvgEpgUrl?: any;
  tvgEpgShift?: any;
  tvgRadio?: any;
  tvgTimeshift?: any;
  tvgArchive?: any;
  tvgTvgPlaylist?: any;
  tvgAspectRatio?: any;
  tvgAudioTrack?: any;
  tvgClosedCaptions?: any;
  tvgClosedCaptionsLanguage?: any;
  tvgClosedCaptionsType?: any;
  tvgContentType?: any;
  tvgCopyright?: any;
  tvgDuration?: any;
  tvgExtXDiscontinuity?: any;
  tvgExtXEndlist?: any;
  tvgExtXKey?: any;
  tvgExtXMediaSequence?: any;
  tvgExtXProgramDateTime?: any;
  tvgExtXVersion?: any;
  tvgGap?: any;
  tvgIndependentSegments?: any;
  tvgMedia?: any;
  tvgMediaSequence?: any;
  tvgPlaylistType?: any;
  tvgStart?: any;
  tvgTargetDuration?: any;
  tvgXByterange?: any;
  tvgXEndlist?: any;
  tvgXKey?: any;
  tvgXMediaSequence?: any;
  tvgXProgramDateTime?: any;
  tvgXVersion?: any;
  tvgResolution?: any;
  tvgFramerate?: any;
};

export const clearEntry = (entry: Entry) => {
  entry.contentURL = "";
  entry.duration = 0;
  entry.tvgId = undefined;
  entry.tvgLogo = undefined;
  entry.tvgName = undefined;
  entry.groupTitle = undefined;
  entry.entryTitle = undefined;
  entry.tvgCountry = undefined;
  entry.tvgLanguage = undefined;
  entry.tvgType = undefined;
  entry.tvgUrl = undefined;
  entry.tvgGroup = undefined;
  entry.tvgEpgid = undefined;
  entry.tvgEpgUrl = undefined;
  entry.tvgEpgShift = undefined;
  entry.tvgRadio = undefined;
  entry.tvgTimeshift = undefined;
  entry.tvgArchive = undefined;
  entry.tvgTvgPlaylist = undefined;
  entry.tvgAspectRatio = undefined;
  entry.tvgAudioTrack = undefined;
  entry.tvgClosedCaptions = undefined;
  entry.tvgClosedCaptionsLanguage = undefined;
  entry.tvgClosedCaptionsType = undefined;
  entry.tvgContentType = undefined;
  entry.tvgCopyright = undefined;
  entry.tvgDuration = undefined;
  entry.tvgExtXDiscontinuity = undefined;
  entry.tvgExtXEndlist = undefined;
  entry.tvgExtXKey = undefined;
  entry.tvgExtXMediaSequence = undefined;
  entry.tvgExtXProgramDateTime = undefined;
  entry.tvgExtXVersion = undefined;
  entry.tvgGap = undefined;
  entry.tvgIndependentSegments = undefined;
  entry.tvgMedia = undefined;
  entry.tvgMediaSequence = undefined;
  entry.tvgPlaylistType = undefined;
  entry.tvgStart = undefined;
  entry.tvgTargetDuration = undefined;
  entry.tvgXByterange = undefined;
  entry.tvgXEndlist = undefined;
  entry.tvgXKey = undefined;
  entry.tvgXMediaSequence = undefined;
  entry.tvgXProgramDateTime = undefined;
  entry.tvgXVersion = undefined;
  entry.tvgResolution = undefined;
  entry.tvgFramerate = undefined;
};
